### ISSUE TITLE
Provide an option to print the delomboked source files

### ISSUE THREAD

**Issue by sleberknight** [sleberknight/delombok-action#3]
This could be a command line flag in the script, e.g. `-p`, that tells the action it should delombok and print the delomboked code to standard out. For the action, this can be an input variable, e.g.

```yaml
- name: Run Delombok
  uses: sleberknight/delombok-action@v0.6.0
  with:
    printDelombokedSource: true
```

The following command can be used to print the files: `find src-delombok -type f -exec cat {} \;` (from this [sample code](https://github.com/sleberknight/github-actions-learning/blob/7a88af09390dcd201597c64884a355b0d8121129/.github/workflows/test-sleberknight-delombok.yml#L26))

**Comment by sleberknight** [comment]
Not sure it's worth it, but could create a very simple action dedicated to printing the delomboked code, e.g. turning this:

```yaml
- name: Print the Delomboked code
  run: find src-delombok -type f -exec cat {} \;
  shell: bash
```
 into this:

```yaml
- name: Print the Delomboked code
  uses: sleberknight/print-delombok@v0.1.0
```

The above assumes there is an action named `print-delombok` with a version `v0.1.0`. While the `find` command is simple, it would be annoying to have to repeat that anywhere you want to print the delomboked code.

The `print-delombok` action must rely on the delomboked code being located in the `src-delombok` directory, which this action currently hard codes. If we parameterize the output location for the delomboked source code (in _this_ action), then the `print-delombok` action could also accept that as input, e.g. in a workflow:

```yaml
- name: Run Delombok
  uses: sleberknight/delombok-action@v0.6.0
  with:
    delombokSourcePath: delombok-source-code

- name: Print the Delomboked code
  uses: sleberknight/print-delombok@v0.1.0
  with:
    delombokSourcePath: delombok-source-code
```

The `delombokSourcePath` input variable would need to be added to this action. I think I read in the Actions documentation there is some way to have an action produce output variables, but can't remember and would need to research that.
